# fly.toml app configuration file generated for papiro-web-server on 2024-07-29T01:40:43-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'visomi.dev'
primary_region = 'qro'

[env]
  PORT = '8080'

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
