baseURL = '/'
languageCode = 'en-us'
title = 'Michael Villalba'
theme = []
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    [languages.en.params]
      locale = 'en'
  [languages.es]
    languageName = 'Español'
    weight = 2
    [languages.es.params]
      locale = 'es'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true
